### ISSUE TITLE
Proposal: make `dim` notation the default in nxdl-to-nyaml

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/nyaml#22]
Currently, when the `dim` keyword with numpy notation is used in an nyaml file and I run a full forwards-backwards cycle of nyaml, the notation is changed to `dimensions` with `rank` and `dim`.

I propose to make the backwards conversion default to the `dim` keyword.

**Comment by RubelMozumder** [comment]
Following up from another issue:

https://github.com/FAIRmat-NFDI/pynxtools/issues/151#issuecomment-1945647528

https://github.com/FAIRmat-NFDI/pynxtools/issues/151#issuecomment-1945900009
